# render.yaml

services:
  - type: pserv
    name: backend-mediasoup-sfu
    runtime: docker
    plan: free # или paid, в зависимости от ваших потребностей
    # Укажите относительный путь к Dockerfile, если он не в корне репо
    # dockerfilePath: ./backend-mediasoup/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      # Добавьте другие переменные окружения, кроме секретных
      # Секретные переменные (например, TURN_CREDENTIAL) лучше задавать в Dashboard Render
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 3001
      - key: ANNOUNCED_IP
        value: # Оставьте пустым или удалите, если автоопределение работает
      - key: ALLOWED_ORIGINS
        value: https://webrtc-video-conference-two.vercel.app,http://localhost:3000
      # - key: CERT_FILE # Не нужны для Services, Render терминирует TLS
      #   value: ...
      # - key: KEY_FILE  # Не нужны для Services, Render терминирует TLS
      #   value: ...
      - key: LOG_LEVEL
        value: info
      - key: MAX_USERS
        value: 8
      - key: MAX_ROOMS
        value: 2
      - key: SESSION_TIMEOUT
        value: 30m
      - key: MEDIASOUP_WORKERS
        value: 2 # Подберите под мощность вашего плана
      # Убедитесь, что диапазон портов соответствует конфигурации mediasoup
      # и вашему Dockerfile EXPOSE (если указали)
    # --- Ключевая часть: открытие портов ---
    # Открываем порт для WebSocket/Sigaling
    - port: 3001
      # protocol: http # или https если ваше приложение терминирует TLS (обычно нет)
    # Открываем диапазон портов UDP для WebRTC
    - port: 40000-49999
      protocol: udp
    # Открываем диапазон портов TCP для WebRTC (если используете TCP)
    - port: 40000-49999
      protocol: tcp
    # --- Конец открытия портов ---